# Generated by Django 5.1.15 on 2026-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('run_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('criteria', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('errored', 'Errored')], default='running', max_length=20)),
                ('batch_size', models.IntegerField()),
                ('current_batch_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
