# Generated by Django 5.1.15 on 2026-07-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscoveryRun',
            new_name='AgentRuns',
        ),
        migrations.CreateModel(
            name='AgentSteps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('iteration', models.IntegerField()),
                ('tool', models.CharField(max_length=255)),
                ('arguments', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agentruns')),
            ],
        ),
    ]
