# Generated by Django 5.1.15 on 2026-07-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_discoveryrun_agentruns_agentsteps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentRuns',
            new_name='AgentRun',
        ),
        migrations.RenameModel(
            old_name='AgentSteps',
            new_name='AgentStep',
        ),
    ]
