# Generated by Django 5.1.15 on 2026-07-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_agentruns_agentrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('target_doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.CharField(blank=True, max_length=255, null=True)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='agent.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('correction_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('original_value', models.CharField(max_length=255)),
                ('corrected_value', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.CharField(max_length=255)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='agent.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(max_length=255)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.CharField(max_length=255)),
                ('relevance', models.BooleanField()),
                ('privilege', models.CharField(max_length=255)),
                ('issue_tags', models.JSONField()),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField()),
                ('committed', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agent.agentrun')),
                ('superseder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_decisions', to='agent.decision')),
            ],
        ),
    ]
