# Generated by Django 5.1.15 on 2026-07-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auditevent_correction_decision'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='documents.document'),
        ),
    ]
