# Generated by Django 5.1.15 on 2026-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_auditevent_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='payload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
