# Generated by Django 5.1.15 on 2026-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_auditevent_payload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentstep',
            old_name='finished_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='agentrun',
            name='run_type',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='tokens_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='tokens_output',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
