# Generated by Django 5.1.15 on 2026-07-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_rename_finished_at_agentstep_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='field',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='rationale',
        ),
    ]
