# Generated by Django 6.0.6 on 2026-07-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_remove_correction_field_remove_correction_rationale'),
        ('documents', '0002_document_participant_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReviewRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.JSONField(blank=True, null=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='documents.document')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='agent.agentrun')),
            ],
        ),
    ]
