# Generated by Django 6.0.6 on 2026-07-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_humanreviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='current_batch_queue',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
