# Generated by Django 5.1.15 on 2026-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('x_sdoc', models.CharField(blank=True, max_length=255, null=True)),
                ('x_zlid', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('from_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('to_addrs', models.TextField(blank=True, null=True)),
                ('cc_addrs', models.TextField(blank=True, null=True)),
                ('bcc_addrs', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('custodian', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_refs', models.TextField(blank=True, null=True)),
                ('raw_headers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
